### ISSUE TITLE
ModuleNotFoundError: No module named 'utils'

### ISSUE THREAD

**Issue by davidr99** [gpt-omni/mini-omni2#21]
When running
> API_URL=http://0.0.0.0:60808/chat streamlit run webui/omni_streamlit.py

I get this error

```
2024-10-28 23:08:50.479 Uncaught app exception
Traceback (most recent call last):
  File "lib/python3.10/site-packages/streamlit/runtime/scriptrunner/exec_code.py", line 85, in exec_func_with_error_handling
    result = func()
  File "lib/python3.10/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 576, in code_to_exec
    exec(code, module.__dict__)
  File "mini-omni2/webui/omni_streamlit.py", line 18, in <module>
    from utils.vad import get_speech_timestamps, collect_chunks, VadOptions
ModuleNotFoundError: No module named 'utils'
```

**Comment by DENightOne** [comment]
quick fix....just copy webui/omni_streamlit.py in the root folder (where server.py is) and run streamlit run omni_streamlit.py

**Comment by davidr99** [comment]
That fixed that issue, now I just have a new error:
> OSError: [Errno -9996] Invalid input device (no default output device)

**Comment by RobertLau666** [comment]
```
cd mini-omni2
export PYTHONPATH=$(pwd):$PYTHONPATH
```

**Comment by davidr99** [comment]
That fixed the utils issue.
