### ISSUE TITLE
OSError: [Errno -9996] Invalid input device (no default output device)

### ISSUE THREAD

**Issue by davidr99** [gpt-omni/mini-omni2#23]
When running the streamlit program I get this error

```
2024-10-29 10:24:08.462 Uncaught app exception
Traceback (most recent call last):
  File "lib/python3.10/site-packages/streamlit/runtime/scriptrunner/exec_code.py", line 85, in exec_func_with_error_handling
    result = func()
  File "lib/python3.10/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 576, in code_to_exec
    exec(code, module.__dict__)
  File "mini-omni2/webui/omni_streamlit.py", line 371, in <module>
    main()
  File "mini-omni2/webui/omni_streamlit.py", line 335, in main
    recording(status)
  File "mini-omni2/webui/omni_streamlit.py", line 201, in recording
    stream = audio.open(
  File "lib/python3.10/site-packages/pyaudio/__init__.py", line 639, in open
    stream = PyAudio.Stream(self, *args, **kwargs)
  File "lib/python3.10/site-packages/pyaudio/__init__.py", line 441, in __init__
    self._stream = pa.open(**arguments)
OSError: [Errno -9996] Invalid input device (no default output device)
```

**Comment by mini-omni** [comment]
hi, sometimes, when using it for the first time, an 'Input overflowed' error may occur. You can simply click 'start' to retry.

**Comment by davidr99** [comment]
Oh it is not running locally, its running on a server I will try it locally.

**Comment by ranck626** [comment]
I can only use this code on a server, I don't have a GPU locally.

**Comment by davidr99** [comment]
So you run the one part on the server and you run the streamlit on your local PC and point it to the HTTP API on the server.
