### ISSUE TITLE
not found utils folder

### ISSUE THREAD

**Issue by halilugur** [gpt-omni/mini-omni2#30]
Traceback (most recent call last):
  File "/home/halilugur/miniconda3/envs/omni/lib/python3.10/site-packages/streamlit/runtime/scriptrunner/exec_code.py", line 85, in exec_func_with_error_handling
    result = func()
  File "/home/halilugur/miniconda3/envs/omni/lib/python3.10/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 576, in code_to_exec
    exec(code, module.__dict__)
  File "/home/halilugur/mini-omni2/webui/omni_streamlit.py", line 18, in <module>
    from utils.vad import get_speech_timestamps, collect_chunks, VadOptions
ModuleNotFoundError: No module named 'utils'

**Comment by Gittomon** [comment]
I am having same issue, I tried placing __init__.py in the utils folder still getting the same error.. how to fix this

**Comment by Gittomon** [comment]
well well well. GOT the FIX 

quick fix....just copy webui/omni_streamlit.py in the root folder (where server.py is) and run streamlit run omni_streamlit.py

from oneof the closed issue section someone said this thanks....
