### ISSUE TITLE
litgpt/tokenizer.py报错NotImplementedError

### ISSUE THREAD

**Issue by WJMismybestfriend** [gpt-omni/mini-omni2#41]
已经从HF上拉下来模型、分词等文件，但执行报以下错误。python为3.10
(myenv) (base) root@41661e173995:/home../mini-omni2-main# python3 server.py --ip '0.0.0.0' --port 60808
Traceback (most recent call last):
  File "/home../mini-omni2-main/server.py", line 95, in <module>
    fire.Fire(serve)
  File "/home/.../mini-omni2-main/myenv/lib/python3.10/site-packages/fire/core.py", line 135, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/home/.../mini-omni2-main/myenv/lib/python3.10/site-packages/fire/core.py", line 468, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/home/.../mini-omni2-main/myenv/lib/python3.10/site-packages/fire/core.py", line 684, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/home/../mini-omni2-main/server.py", line 90, in serve
    OmniChatServer(ip, port=port,run_app=True, device=device)
  File "/home/../mini-omni2-main/server.py", line 22, in __init__
    self.client = OmniVisionInference(ckpt_dir, device)
  File "/home/../mini-omni2-main/inference_vision.py", line 83, in __init__
    self.fabric, self.model, self.text_tokenizer, self.snacmodel, self.whispermodel = load_model(ckpt_dir, device)
  File "/home/../mini-omni2-main/inference.py", line 358, in load_model
    text_tokenizer = Tokenizer(ckpt_dir)
  File "/home/../mini-omni2-main/litgpt/tokenizer.py", line 64, in __init__
    raise NotImplementedError
NotImplementedError

**Comment by mini-omni** [comment]
看起来你没有下载所有的文件，以下文件都是需要的
<img width="450" alt="image" src="https://github.com/user-attachments/assets/7d16b95a-2ed2-4c93-9d0b-cfcfe82c0805">

**Comment by HeywardLiu** [comment]
> 看起来你没有下载所有的文件，以下文件都是需要的 <img alt="image" width="450" src="https://private-user-images.githubusercontent.com/179588335/385820810-7d16b95a-2ed2-4c93-9d0b-cfcfe82c0805.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ1MjMxOTMsIm5iZiI6MTczNDUyMjg5MywicGF0aCI6Ii8xNzk1ODgzMzUvMzg1ODIwODEwLTdkMTZiOTVhLTJlZDItNGM5My05ZDBiLWNmY2ZlODJjMDgwNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIxOFQxMTU0NTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03ZWM2NDMyNTYwYjdiZDY1NTcwN2VlODNlMmJiMjc4MDgxNzFkMmVjNDY3OTQwNWMyMzBlZTc1YjIyYWY1NzYyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.iz3DbK35EaBnI99z8vQOgG0EBSqs-vmN6R9LJrIfhpg">

Hi, can you explain how to install those files? thanks!

**Comment by mini-omni** [comment]
@HeywardLiu you can download it from: https://huggingface.co/gpt-omni/mini-omni2/tree/main
